branch-defaults:
  default:
    environment: miz2-new
    group_suffix: null
  master:
    environment: miz2017
global:
  application_name: miz2
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: null
